name: student_cabinet_app
description: "Кабинет студента ГБПОУ ТПЭК"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # listeners
  flutter_bloc: ^9.0.0

  #network
  dio: ^5.7.0
  url_launcher: ^6.2.2

  # pdf
  syncfusion_flutter_core: ^29.2.5
  syncfusion_flutter_pdf: ^29.2.5
  pdf: ^3.10.7

  flutter_localizations:
    sdk: flutter

  #extensions
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3

  #di
  get_it: ^8.0.3

  #services
  package_info_plus: ^6.0.0
  device_info_plus: ^9.1.2
  intl: ^0.19.0

  # icons_reader
  flutter_svg: ^2.0.9

  #widgets
  dropdown_search: ^5.0.6
  searchfield: ^1.1.6
  pin_code_fields: ^8.0.1
  overlay_support: ^2.1.0
  fluttertoast: ^8.1.1

  #storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

  #icons
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/